### ISSUE TITLE
bot is not logging in despite correct password

### ISSUE THREAD

**Issue by drx19** [austinsimpson/evga-bot#1]
Error: Please contact to the Website manager.

![image](https://user-images.githubusercontent.com/71615615/93826833-13de7100-fc36-11ea-89bc-6787c69d0610.png)

**Comment by austinsimpson** [comment]
I've ran into this too, but if I retry enough times it seems to log in.

**Comment by austinsimpson** [comment]
https://twitter.com/EVGA_JacobF/status/1308815814879895553. This is an issue on EVGA's end.
